project:
  type: book

book:
  title: "Data Analysis for Food Science"
  date: "5.9.2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
    - cosmo
    - style.scss
   # mainfont: serif
    
    code-fold: show
    code-line-numbers: true
    code-tools: true
    grid: 
      sidebar-width: 250px # Max width of left sidebar (standard is 250px)
      body-width: 1000px # Max width of body (standard is 800px)
      margin-width: 300px # Max width of right sidebar (standard is 250px)
      gutter-width: 4em #Max width of space between grid components (standard is 1.5em)
  pdf:
    documentclass: scrreprt




